version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip e2e]"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip e2e]"

  - package-ecosystem: "npm"
    directory: "/UI"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip e2e]"

  - package-ecosystem: "npm"
    directory: "/website"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip e2e]"
