area:
  - "CLI"
  - "cluster"
  - "helm"
  - "GUI"
  - "policy"
  - "cluster-api"
  - "monitoring"
  - "docs"

kind:
  - "bug"
  - "feature"
  - "enhancement"

priority:
  - "low"
  - "mid"
  - "high"
