
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-undistro-io-v1alpha1-cluster
  failurePolicy: Fail
  name: mcluster.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-undistro-io-v1alpha1-defaultpolicies
  failurePolicy: Fail
  name: mdefaultpolicies.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - defaultpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-undistro-io-v1alpha1-helmrelease
  failurePolicy: Fail
  name: mhelmrelease.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmreleases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-config-undistro-io-v1alpha1-provider
  failurePolicy: Fail
  name: mprovider.undistro.io
  rules:
  - apiGroups:
    - config.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-undistro-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-undistro-io-v1alpha1-defaultpolicies
  failurePolicy: Fail
  name: vdefaultpolicies.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - defaultpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-undistro-io-v1alpha1-helmrelease
  failurePolicy: Fail
  name: vhelmrelease.undistro.io
  rules:
  - apiGroups:
    - app.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmreleases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-config-undistro-io-v1alpha1-provider
  failurePolicy: Fail
  name: vprovider.undistro.io
  rules:
  - apiGroups:
    - config.undistro.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providers
  sideEffects: None
