
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
    - port: 2020
      targetPort: 2020
  selector:
    control-plane: controller-manager
