{{ if .Values.ingress.enabled -}}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: undistro-ingress
  namespace: undistro-system
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  virtualhost:
    fqdn: {{.Values.ingress.fqdn}}
    corsPolicy:
        allowCredentials: true
        allowOrigin:
          - "*" # allows any origin
        allowMethods:
          - "*"
        allowHeaders:
          - "*"
        exposeHeaders:
          - "*"
        maxAge: "10m" # preflight requests can be cached for 10 minutes.
  routes:
    - conditions:
      - prefix: /
      enableWebsockets: true
      permitInsecure: true
      services:
        - name: undistro-webhook-service
          port: 2020
{{- end -}}