{{- if .Values.ingress.enabled -}}
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations: 
    {{if .Values.local}}
    cert-manager.io/cluster-issuer: selfsigned
    {{else}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{end}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: undistro-ingress
  namespace: undistro-system
spec: 
  rules: 
    - 
      http: 
        paths: 
          - 
            backend: 
              serviceName: undistro-webhook-service
              servicePort: 2020 
            path: /
            pathType: Prefix
  tls: 
    - 
      hosts: 
        - {{.Values.ingress.host}}
      secretName: undistro-ingress-cert
{{- end -}}