{{- if .Values.ingress.enabled -}}
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/custom-response-headers: Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  name: undistro-ingress
  namespace: undistro-system
spec: 
  rules: 
    - 
      http: 
        paths: 
          - 
            backend: 
              serviceName: undistro-webhook-service
              servicePort: 2020 
            path: /
            pathType: Prefix
  tls: 
    - 
      hosts: 
        - {{.Values.ingress.host}}
      secretName: undistro-ingress-cert
{{- end -}}