{{- if .Values.ingress.enabled -}}
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations:    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: undistro-ingress
  namespace: undistro-system
spec: 
  rules: 
    - 
      http: 
        paths: 
          - 
            backend: 
              serviceName: undistro-webhook-service
              servicePort: 2020 
            path: /
            pathType: Prefix
  tls: 
    - 
      hosts:
        - localhost
        - ingress.local
        - undistro.local
        - undistro.internal
      secretName: undistro-ingress-cert
{{- end -}}