{{- if .Values.local -}}
--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: undistro-local-clusterissuer
spec: 
  selfSigned: {}
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: ca-undistro
  namespace: undistro-system
spec: 
  commonName: "UnDistro Local Authority - ECC Root"
  isCA: true
  issuerRef: 
    group: cert-manager.io
    kind: ClusterIssuer
    name: undistro-local-clusterissuer
  privateKey: 
    algorithm: ECDSA
    size: 256
  secretName: ca-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: undistro-local-issuer
  namespace: undistro-system
spec:
  ca:
    secretName: ca-secret
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: localhost-cert
  namespace: undistro-system
spec: 
  commonName: "UnDistro Local Authority - ECC Root"
  dnsNames:
    {{- range .Values.ingress.hosts }}
      - {{ . }}
    {{- end }}
  issuerRef: 
    kind: Issuer
    name: undistro-local-issuer
  secretName: undistro-ingress-cert
{{- end -}}