# permissions for end users to edit auths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-editor-role
rules:
- apiGroups:
  - auth.undistro.io
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.undistro.io
  resources:
  - auths/status
  verbs:
  - get
