# permissions for end users to edit defaultpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultpolicies-editor-role
rules:
- apiGroups:
  - app.undistro.io
  resources:
  - defaultpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.undistro.io
  resources:
  - defaultpolicies/status
  verbs:
  - get
