# permissions for end users to view defaultpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: defaultpolicies-viewer-role
rules:
- apiGroups:
  - app.undistro.io
  resources:
  - defaultpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.undistro.io
  resources:
  - defaultpolicies/status
  verbs:
  - get
