# permissions for end users to edit helmreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmrelease-editor-role
rules:
- apiGroups:
  - getupcloud.com
  resources:
  - helmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - getupcloud.com
  resources:
  - helmreleases/status
  verbs:
  - get
