# permissions for end users to edit identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identity-editor-role
rules:
- apiGroups:
  - app.undistro.io
  resources:
  - identities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.undistro.io
  resources:
  - identities/status
  verbs:
  - get
