--- 
apiVersion: v1
kind: ConfigMap
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-static-config
  namespace: {{ .Values.metadata.namespace }}
data: 
  pinniped.yaml: |-
      apiGroupSuffix: pinniped.dev
      names:
        defaultTLSCertificateSecret: pinniped-supervisor-default-tls-certificate
      labels: {"app":"pinniped-supervisor"}
