--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  labels: 
    app: pinniped-supervisor
  name: pinniped-supervisor
  namespace: undistro-system
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pinniped-supervisor
subjects: 
  - 
    kind: ServiceAccount
    name: pinniped-supervisor
    namespace: undistro-system
