---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
    name: nginx
    namespace: undistro
spec:
  clusterName: undistro/example-ec2
  targetNamespace: undistro
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: nginx-ingress
    version: 3.30.0
  autoUpgrade: true
  
---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
    name: kubernetes-dashboard
    namespace: undistro
spec:
  clusterName: undistro/example-ec2
  targetNamespace: undistro
  dependencies: 
    - apiVersion: app.undistro.io/v1alpha1
      kind: HelmRelease
      name: nginx
      namespace: undistro
  chart:
    repository: https://kubernetes.github.io/dashboard
    name: kubernetes-dashboard
    version: 4.0.0
  autoUpgrade: true
  afterApplyObjects:
    -
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dashboard-access
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: undistro-quickstart-dash
          namespace: default 
  values:
    ingress:
      enabled: true
    serviceAccount:
      name: undistro-quickstart-dash