apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: default
spec:
  chart:
    repository: https://kubernetes.github.io/dashboard
    name: kubernetes-dashboard
    version: 3.0.0
  afterApplyObjects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dashboard-access
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: undistro-quickstart-dash
          namespace: default
  values:
    serviceAccount:
      name: undistro-quickstart-dash