apiVersion: undistro.io/v1alpha1
kind: Cluster
metadata:
  name: undistro-quickstart
  namespace: default
spec:
  kubernetesVersion: v1.18.2
  cniName: calico
  controlPlaneNode:
    replicas: 3
    machineType: t3.large
  workerNodes:
    - replicas: 3
      machineType: t3.large
      autoscale:
        enabled: true
        minSize: 1
        maxSize: 10
  infrastructureProvider:
    name: aws
    sshKey: undistro
    env:
      - name: AWS_ACCESS_KEY_ID
        value: ""
      - name: AWS_SECRET_ACCESS_KEY
        value: ""