---
apiVersion: undistro.io/v1alpha1
kind: Cluster
metadata:
  name: undistro-quickstart
  namespace: default
spec:
  kubernetesVersion: v1.16.13
  cniName: calico
  workerNodes:
    - replicas: 3
      machineType: t3.large
  bootstrapProvider:
    name: eks
  infrastructureProvider:
    name: aws
    sshKey: undistro
    env:
      - name: AWS_ACCESS_KEY_ID
        value: ""
      - name: AWS_SECRET_ACCESS_KEY
        value: ""
      - name: EXP_EKS
        value: "true"
      - name: EXP_EKS_IAM
        value: "true"
      - name: EXP_EKS_ADD_ROLES
        value: "true"
      
---
apiVersion: undistro.io/v1alpha1
kind: HelmRelease
metadata:
  name: alb
  namespace: default
spec:
  clusterName: default/undistro-quickstart
  chart:
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    name: aws-alb-ingress-controller
    version: 1.0.2
    values:
      autoDiscoverAwsRegion: true
      autoDiscoverAwsVpcID: true
      clusterName: undistro-quickstart
      
---
apiVersion: undistro.io/v1alpha1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: default
spec:
  clusterName: default/undistro-quickstart
  chart:
    repository: https://kubernetes.github.io/dashboard
    name: kubernetes-dashboard
    version: 2.0.3
  values:
    ingress:
      enabled: true

