apiVersion: getupcloud.com/v1alpha1
kind: Cluster
metadata:
  name: undistro-quickstart
  namespace: default
spec:
  kubernetesVersion: v1.18.2
  cniName: calico
  controlPlaneNode:
    replicas: 3
    machineType: t3.large
  workerNodes:
    - replicas: 3
      machineType: t3.large
  infrastructureProvider:
    name: aws
    sshKey: undistro
    env:
      - name: AWS_ACCESS_KEY_ID
        value: ""
      - name: AWS_SECRET_ACCESS_KEY
        value: ""

---
apiVersion: getupcloud.com/v1alpha1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  clusterName: default/undistro-quickstart
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.15.0

---
apiVersion: getupcloud.com/v1alpha1
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: default
spec:
  clusterName: default/undistro-quickstart
  dependencies:
    -
      apiVersion: getupcloud.com/v1alpha1
      kind: HelmRelease
      name: nginx
  afterApplyObjects:
    -
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: dashboard-access
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: undistro-quickstart-dash
          namespace: default  
  chart:
    repository: https://kubernetes.github.io/dashboard
    name: kubernetes-dashboard
    version: 2.6.0
  values:
    ingress:
      enabled: true
    serviceAccount:
      name: undistro-quickstart-dash