---
{{$uuid := uuidv4}}
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "{{.Name}}"
  namespace: "{{.Namespace}}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSManagedCluster
    name: "{{.Name}}"
    namespace: "{{.Namespace}}"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "{{.Name}}-control-plane"
    namespace: "{{.Namespace}}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedCluster
metadata:
  name: "{{.Name}}"
  namespace: "{{.Namespace}}"
  
{{$bastion := .GetBastion}}
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "{{.Name}}-control-plane"
  namespace: "{{.Namespace}}"
spec:
  sshKeyName: "{{.Spec.InfrastructureProvider.SSHKey}}"
  region: '{{variable "AWS_REGION"}}'
  version: "{{.Spec.KubernetesVersion}}"
  bastion:
    enabled: {{$bastion.Enabled}}
    disableIngressRules: {{$bastion.DisableIngressRules}}
    instanceType: {{$bastion.InstanceType}}
    allowedCIDRBlocks:
    {{range $bastion.AllowedCIDRBlocks}}
      - {{.}}
    {{end}}
  {{if .Spec.Network}}
  networkSpec:
    vpc:
      id: {{.Spec.Network.VPC}}
    subnets:
    {{range .Spec.Network.Subnets}}
    - id: {{.}}
    {{end}}
  {{end}}

{{$name := .Name}}
{{$namespace := .Namespace}}
{{$k8s := .Spec.KubernetesVersion}}
{{$sshKey := .Spec.InfrastructureProvider.SSHKey}}
{{range $index, $element := .Spec.WorkerNodes}}
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: "{{$name}}-md-{{$index}}"
  namespace: "{{$namespace}}"
spec:
  clusterName: "{{$name}}"
  replicas: {{$element.Replicas}}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "{{$name}}"
      version: "{{$k8s}}"
      {{if $element.Subnet}}
      subnet: 
        id: {{$element.Subnet}}
      {{end}}
      bootstrap:
        configRef:
          name: "{{$name}}-md-{{$index}}"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: EKSConfigTemplate
          namespace: "{{$namespace}}"
      infrastructureRef:
        name: "{{$name}}-md-{{$index}}"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        namespace: "{{$namespace}}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: "{{$name}}-md-{{$index}}"
  namespace: "{{$namespace}}"
spec:
  template:
    spec:
      instanceType: "{{$element.MachineType}}"
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: "{{$sshKey}}"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: EKSConfigTemplate
metadata:
  name: "{{$name}}-md-{{$index}}"
  namespace: "{{$namespace}}"
spec:
  template: {}
{{end}}