--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  labels: 
    name: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-aggregated-api-server
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-aggregated-api-server
subjects: 
  - 
    kind: ServiceAccount
    name: {{ .Values.metadata.name }}
    namespace: {{ .Values.metadata.namespace }}
