--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge-api
  namespace: undistro-system
spec: 
  ports: 
    - 
      port: 443
      protocol: TCP
      targetPort: 8443
  selector: 
    app: pinniped-concierge
  type: ClusterIP
