--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-api
  namespace: {{ .Values.metadata.namespace }}
spec: 
  ports: 
    - 
      port: 443
      protocol: TCP
      targetPort: 8443
  selector: 
    app: {{ .Values.metadata.labels.app }}
  type: ClusterIP
