--- 
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: v1alpha1.login.concierge.pinniped.dev
spec: 
  group: login.concierge.pinniped.dev
  groupPriorityMinimum: 9900
  service: 
    name: {{ .Values.metadata.name }}-api
    namespace: {{ .Values.metadata.namespace }}
    port: 443
  version: v1alpha1
  versionPriority: 15
