---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.metadata.name }}-cluster-info-lister-watcher
  namespace: kube-public
  labels:
    name: {{ .Values.metadata.labels.app }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch