---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.metadata.name }}-cluster-info-lister-watcher
  namespace: kube-public
  labels:
    app: {{ .Values.metadata.labels.app }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.metadata.name }}-cluster-info-lister-watcher
  apiGroup: rbac.authorization.k8s.io
