--- 
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-config
spec: 
  impersonationProxy: 
    mode: enabled
    service: 
      annotations: ~
      type: ClusterIP
