--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge
  namespace: undistro-system
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: pinniped-concierge
  template: 
    metadata: 
      annotations: 
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels: 
        app: pinniped-concierge
    spec: 
      affinity: 
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution: 
            - 
              podAffinityTerm: 
                labelSelector: 
                  matchLabels: 
                    app: pinniped-concierge
                topologyKey: kubernetes.io/hostname
              weight: 50
      containers: 
        - 
          args: 
            - "--config=/etc/config/pinniped.yaml"
            - "--downward-api-path=/etc/podinfo"
          image: "projects.registry.vmware.com/pinniped/pinniped-server:0.9.1"
          imagePullPolicy: IfNotPresent
          livenessProbe: 
            failureThreshold: 5
            httpGet: 
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 15
          name: pinniped-concierge
          readinessProbe: 
            failureThreshold: 3
            httpGet: 
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 3
          resources: 
            limits: 
              cpu: 100m
              memory: 128Mi
            requests: 
              cpu: 100m
              memory: 128Mi
          volumeMounts: 
            - 
              mountPath: /etc/config
              name: config-volume
            - 
              mountPath: /etc/podinfo
              name: podinfo
      securityContext: 
        runAsGroup: 1001
        runAsUser: 1001
      serviceAccountName: pinniped-concierge
      tolerations: 
        - 
          key: CriticalAddonsOnly
          operator: Exists
        - 
          effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes: 
        - 
          configMap: 
            name: pinniped-concierge-config
          name: config-volume
        - 
          downwardAPI: 
            items: 
              - 
                fieldRef: 
                  fieldPath: metadata.labels
                path: labels
              - 
                fieldRef: 
                  fieldPath: metadata.name
                path: name
              - 
                fieldRef: 
                  fieldPath: metadata.namespace
                path: namespace
          name: podinfo
