--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge-extension-apiserver-authentication-reader
  namespace: kube-system
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects: 
  - 
    kind: ServiceAccount
    name: pinniped-concierge
    namespace: undistro-system
