--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge-kube-cert-agent
  namespace: undistro-system
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pinniped-concierge-kube-cert-agent
subjects: 
  - 
    kind: ServiceAccount
    name: pinniped-concierge-kube-cert-agent
    namespace: undistro-system
