--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-kube-cert-agent
  namespace: {{ .Values.metadata.namespace }}
rules: 
  - 
    apiGroups: 
      - policy
    resources: 
      - podsecuritypolicies
    verbs: 
      - use
