--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  labels: 
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-kube-system-pod-read
  namespace: kube-system
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.metadata.name }}-kube-system-pod-read
subjects: 
  - 
    kind: ServiceAccount
    name: {{ .Values.metadata.name }}
    namespace: {{ .Values.metadata.namespace }}
