--- 
apiVersion: v1
kind: ServiceAccount
metadata: 
  labels: 
    name: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-kube-cert-agent
  namespace: {{ .Values.metadata.namespace }}
