--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  labels: 
    name: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-kube-cert-agent
  namespace: {{ .Values.metadata.namespace }}
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.metadata.name }}-kube-cert-agent
subjects: 
  - 
    kind: ServiceAccount
    name: {{ .Values.metadata.name }}-kube-cert-agent
    namespace: {{ .Values.metadata.namespace }}
