--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge-kube-system-pod-read
  namespace: kube-system
rules: 
  - 
    apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - get
      - list
      - watch
