--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  labels: 
    app: pinniped-concierge
  name: pinniped-concierge-kube-cert-agent
  namespace: undistro-system
rules: 
  - 
    apiGroups: 
      - policy
    resources: 
      - podsecuritypolicies
    verbs: 
      - use
