--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  labels: 
    name: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-kube-system-pod-read
  namespace: kube-system
rules: 
  - 
    apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - get
      - list
      - watch
