---
apiVersion: app.undistro.io/v1alpha1
kind: HelmRelease
metadata:
  annotations:
    security.undistro.io/kyverno: ""
  name: "kyverno-{{.Cluster.Name}}"
  namespace: "{{.Cluster.Namespace}}"
spec:
  {{if ne .Cluster.Namespace "undistro-system"}}
  {{if ne .Cluster.Name "management"}}
  clusterName: "{{.Cluster.Namespace}}/{{.Cluster.Name}}"
  {{end}}
  {{end}}
  releaseNme: kyverno
  targetNamespace: kyverno
  chart:
    repository: "https://registry.undistro.io/chartrepo/library"
    name: kyverno
    version: 1.3.6
  values:
    infraNode: "{{.Cluster.HasInfraNodes}}"
    fullnameOverride: kyverno
    namespace: kyverno
    resources:                 
      limits:                  
        memory: 2Gi            
        cpu: 2000m             
      requests:                
        cpu: 500m              
        memory: 500Mi