replicaCount: 2

image:
  repository: "projects.registry.vmware.com/pinniped/pinniped-server"
  pullPolicy: IfNotPresent  
  tag: "v0.9.1"

metadata:
  name: pinniped-concierge
  namespace: undistro-system
  labels:
    app: pinniped-concierge

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

service:
  type: ClusterIP
  port: 443
