devEnv: false
ingress:
  enabled: true
  fqdn: undistro.local
  annotations:
    kubernetes.io/ingress.class: contour
    projectcontour.io/ingress.class: contour
resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: "0.5"
    memory: 256Mi
image:
  repository: getupioundistro/undistro
  tag: v0.26.6
  pullPolicy: IfNotPresent
  pullSecrets: []
