devEnv: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: cantour
    projectcontour.io/websocket-routes: /
resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: "0.5"
    memory: 256Mi
image:
  repository: getupioundistro/undistro
  tag: v0.25.4
  pullPolicy: IfNotPresent
  pullSecrets: []
