devEnv: false
ingress:
  enabled: true
resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: "0.5"
    memory: 256Mi
image:
  repository: getupioundistro/undistro
  tag: v0.25.4
  pullPolicy: IfNotPresent
  pullSecrets: []