local: false
prometheus:
  enabled: false
ingress:
  enabled: true
  host: localhost
  tls:
    email: undistro@getup.io
  annotations: {}
resources:
  limits:
    cpu: "2"
    memory: 1024Mi
  requests:
    cpu: "0.5"
    memory: 256Mi
image:
  repository: registry.undistro.io/library/undistro
  tag: v0.30.0
  pullPolicy: IfNotPresent
  pullSecrets: []
