name: Tests

on:
  push:
    branches: ["*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Set up Node 15
        uses: actions/setup-node@v2
        with:
          node-version: "15"
        id: node

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)        
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)        
        run: ct lint --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)        
        run: ct install --all

      - name: Get dependencies
        run: go mod download

      - name: Build CLI
        run: make cli

      - name: Build Manager
        run: make manager

      - name: Build UI
        working-directory: ./UI
        run: |
          yarn
          yarn build

      - name: Test
        run: make test

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
