name: Tests E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: go mod download

      - name: Build CLI and add path
        run: |
          make cli
          echo "GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin" >> $GITHUB_PATH

      - name: Install Kind and create cluster
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.10.0
          ./hack/kind.sh

      - name: Run E2E
        working-directory: ./e2e
        env:
          E2E_AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
          E2E_AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}
        run: |
          go test -e2e ./...
