name: Tests E2E

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
    branches: ["main"]

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get dependencies
        run: go mod download

      - name: vars from bash
        run: ./hack/version.sh

      - name: Build CLI and add path
        run: |
          make cli
          echo "GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin" >> $GITHUB_PATH

      - name: Install Kind and create cluster
        run: |
          GO111MODULE="on" go get sigs.k8s.io/kind@v0.10.0
          ./hack/kind.sh

      - name: Configure AWS credentials for E2E
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run E2E
        working-directory: ./e2e
        if: "!contains(github.event.head_commit.message, 'skip e2e')"
        env:
          E2E_AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
          E2E_AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}
          E2E_PEM: ${{ secrets.E2E_PEM }}
        run: |
          echo $E2E_PEM > undistro.pem
          go install github.com/onsi/ginkgo/ginkgo
          ginkgo -v -trace -- -e2e
